package jedai.domain.security;

// Generated Feb 5, 2009 9:48:08 AM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contacts generated by hbm2java
 */
@Entity
@Table(name = "contacts")
public class Contacts implements java.io.Serializable {

	private long id;
	private String contactName;
	private String email;

	public Contacts() {
	}

	public Contacts(long id, String contactName, String email) {
		this.id = id;
		this.contactName = contactName;
		this.email = email;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "contact_name", nullable = false, length = 50)
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
